### ISSUE TITLE
"autocommit cannot be used inside a transaction" error "hides" the actual error?

### ISSUE THREAD

**Issue by YAmikep** [heroku-python/django-postgrespool#24]
Hi,

I was having a `autocommit cannot be used inside a transaction` error.
It was hard to find the reason but when I removed django_postgrespool (`#DATABASES['default']['ENGINE'] = 'django_postgrespool'``), the error was finally more explicit about an integrity error. I was able to fix it and the error was gone.

Why the error is not the actual error when using django_postgrespool? Isn't it possible to raise the message of the real error?

Thanks

**Comment by YAmikep** [comment]
Is there still anybody maintaining this app?

**Comment by admosity** [comment]
Ran into the same problem. Been scratching my head for hours wondering what went wrong.

**Comment by tbpalsulich** [comment]
+1. Having the same issue when incorrectly attempting to create a model with a null field value.

**Comment by mlynch** [comment]
@tpalsulich you nailed it. For anyone else having the same issuing when using django-postgrespool, this error is hiding a different DB error. For me, I had a table that had some NOT NULL constraints on it incorrectly, and that was bubbling up and causing this issue.

**Comment by thewayiam** [comment]
Same here, while insert duplicate
`IntegrityError: duplicate key value violates unique constraint`

**Comment by grvhi** [comment]
+1 - also getting this issue, except that in my case, changing the db settings back to `django.db.backends.postgresql_psycopg2` removes the error altogether (i.e. there is no underlying issue)

EDIT: Turns out that django_postgrespool seems to squash almost all DB-level exceptions and return this exception instead. Sadly, I don't have time right now to see if there's a fix.....

**Comment by otanner** [comment]
I ran into this problem also. I debugged the issue a little bit and I think the problem is using the Django's postgresql_psycopg2.base.DatabaseWrapper's is_usable() method.

If there is an error in the query a rollback is to be performed. Django-postgrespool's rollback method uses DatabaseWrapper class' is_usable() method to check if the connection is usable and the rollback can be performed. How ever, the is_usable() method is internally using "SELECT 1" to check if the connection is usable but after the query error "SELECT 1" cannot be executed (postgres prints "ERROR:  current transaction is aborted, commands ignored until end of transaction block"), so in this case is_usable() always returns False. And that's the reason the django-postgrespool's rollback is never executed either, and autocommit is tried to set True even when the connection is actually still in a transaction.

This can be tested by removing is_usable() check from _rollback method in django-postgrespool's DatabaseWrapper class. After that you see the real error message.

To fix this we would need to change the way rollback is checking database connection status. Either by overriding the is_usable() method or changing rollback to use some other style.

**Comment by ghost** [comment]
It looks like the handling of IntegrityErrors is broken in django-postgrespool after Django 1.6.  The symptoms match the descriptions above, and the DB connection ends up in a bad state.  All queries after an IntegrityError fail.

However, since 1.6 has connection pooling built in, just don't use django-postgrespool.

**Comment by brockhaywood** [comment]
+1

**Comment by CrazyPython** [comment]
+1 Anybody still monitoring this?

**Comment by kennygoff** [comment]
+1 Bueller?

**Comment by avorio** [comment]
I just ran into the same issue right now which was solved by removing

``` python
DATABASES['default']['ENGINE'] = 'django_postgrespool'
```

from my `settings.py` file.

**Comment by andrelramos** [comment]
Ty avorio, solved my problem =D

**Comment by CrazyPython** [comment]
@andrelramos You're "fixing it" by not using postgrespool anymore.

**Comment by kennethreitz** [comment]
If anyone sends a pull request that fixes this ( https://github.com/kennethreitz/django-postgrespool/issues/24#issuecomment-75400109 ), I will be more than happy to merge.

**Comment by ewilazarus** [comment]
Bump

**Comment by TheJKFever** [comment]
@kennethreitz Does https://github.com/kennethreitz/django-postgrespool/pull/29 solve the issue? Our organization has disabled `postgrespool` because of this issue. It would be great if this solved it and we could merge this in. Thanks!

**Comment by andrelramos** [comment]
@CrazyPython sarcasm
